ceylon/ceylon#6169 (NoClassDefFoundError for remote repository):
Move to Tycho 0.24 and add a fixed repository for transitive optional
dependencies we don't use (especially `sun.misc`)